version: '3.4'

services:
  result:
    image: result
    build:
      context: result
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
