
name: Docker Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: docker build vote     
        run:  docker build ./vote -t votetag
  
      - name: docker build worker
        run: docker build ./worker -t workertag
      
      - name: docker build seed
        run: docker build ./seed-data -t seedtag
      
      - name: docker build result
        run: docker build ./result -t resulttag

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: latest, ${{ github.run_number }}
